### ISSUE TITLE
Cannot find com.gmail.nuclearcat1337.anniPro.anniEvents.AnnihilationEvent

### ISSUE THREAD

**Issue by FinestAF** [MrLittleKitty/AnnihilationPro#1]
trying to recode the plugin but i cannot find that directory

buildpath spigot 1.8.8

**Comment by MrLittleKitty** [comment]
https://github.com/MrLittleKitty/AnnihilationPro/blob/master/Annihilation/src/com/gmail/nuclearcat1337/anniPro/anniEvents/AnniEvent.java
