### ISSUE TITLE
EnderFurnace 1.12

### ISSUE THREAD

**Issue by FinestAF** [MrLittleKitty/AnnihilationPro#2]
Hey im trying to make the ender furnace work on 1.12

Can you please tell me what i need to change in the class, sorry i am new to coding

**Comment by FinestAF** [comment]
` public Furnace_v1_12_R1(final Player p) {
        final EntityPlayer player = ((CraftPlayer)p).getHandle();
        this.owningPlayer = player;
        this.world = player.world;
        super.a("Ender Furnace");`

does not work for 1.12.2

**Comment by MrLittleKitty** [comment]
I have no idea. You will have to figure that out yourself.
