### ISSUE TITLE
Good source code but 2 questions

### ISSUE THREAD

**Issue by samueldon720** [MrLittleKitty/AnnihilationPro#3]
Hey i really liked your source code and found it very helpful.

However
 
1) Where is the chat layout located

2) Nametags show while invis i have tried
player.setCustomNameVisible(false);
also i tried setting names to "" but it does not work either.
but this does not help!

Please can you help me
Thankf for reading

**Comment by MrLittleKitty** [comment]
1. https://github.com/MrLittleKitty/AnnihilationPro/blob/master/Annihilation/src/com/gmail/nuclearcat1337/anniPro/anniGame/GameListeners.java#L119

2.
I don't know how to fix that just from your description.
